### ISSUE TITLE
Width and auto column size for dockerized container

### ISSUE THREAD

**Issue by kenneweg** [adamchainz/django-rich#142]
### Python Version

3.12

### Django Version

4.1

### Description

Width is not properly detected for dockerized container. I can manually set the columns variable, but this is not a solution for multiple users.

**Comment by adamchainz** [comment]
This sounds like a Rich issue, not a Django-rich one, so gonna close this. Did you check the Rich docs and issue tracker? It sounds like your container may be missing some basic Unixy configuration that prevents such detection.
