### ISSUE TITLE
Style subtest results

### ISSUE THREAD

**Issue by smithdc1** [adamchainz/django-rich#219]
### Python Version

3.12

### Django Version

5.1

### Package Version

1.9

### Description

Since adding the rich django test runner cPython has added a new method specially for subtests. 

I think broadly we need to copy this method over and add rich formatting.

https://github.com/python/cpython/blob/main/Lib%2Funittest%2Frunner.py#L64

I'm happy to work on this. However, we're off to London for a couple days this week. I can start looking at it at the weekend.

**Comment by adamchainz** [comment]
Sounds good! Let’s add a [diffing unit test](https://adamj.eu/tech/2024/04/26/python-diffing-unit-test/) to ensure our method stays in sync.
